### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [hiroru/senpai-zsh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by sergibarroso** [comment]
Will do it when is ready 👍 I'll keep you posted

**Comment by unixorn** [comment]
Cool, thanks!

**Comment by sergibarroso** [comment]
Added in #2ea8f7d
