### ISSUE TITLE
theme name must be ZSH_THEME="hiroru/senpai-zsh"

### ISSUE THREAD

**Issue by ashkrosh** [hiroru/senpai-zsh#4]
trying to load ZSH_THEME="senpai-zsh/senpai" using antibody it fails because can't find such github repository. Changing the name to "hiroru/senpai-zsh" fixes this. 
Please correct the README file also

**Comment by sergibarroso** [comment]
Hi @ashkrosh , I'll fix that Today. Thanks for the tip ;-)
